### ISSUE TITLE
Table customization features

### ISSUE THREAD

**Issue by awojtas-r** [PumasAI/SummaryTables.jl#53]
I would like to ask for adding few features which definitely enhance user experience:
- possibility to show dataframe as it is, without performing any summary with custom features I'm requesting below
- possibility to add table title, subtitle, footnote
- possibility to use markdown styling on a specific cell, column name etc
- to add color coding functionality (conditional formatting, value > 1 => "red", etc)

I believe those features will help in choosing the package as a first one when working with tables in any publication.

Thanks!

**Comment by jkrumbiegel** [comment]
Hey, thanks for the suggestions! It's better if each of those points has its own issue, so targeted PRs can close them one by one. So I'd ask you to please split this one up and file separate issues. For each subissue, please check if a similar one has been filed already (the color one for example). Thanks!
