### ISSUE TITLE
table_one: "Overall" collumn for each category in "groupby", multiple "groupby" (Question / Feature request)

### ISSUE THREAD

**Issue by PharmCat** [PumasAI/SummaryTables.jl#7]
For example:

```
using SummaryTables

data = (;
    x = [1, 2, 3, 4, 5, 6],
    y = ["a", "a", "b", "b", "c", "c"],
    z = ["d", "e", "d", "e", "d", "e"],
)

table_one(data, :x, groupby = [:y, :z => "Column Z"])
```

Is is possible to get overall statistics for each `:y` category?

Is it possible to get grouping separately for `:y` and`:z` in one table?

**Comment by jkrumbiegel** [comment]
> Is is possible to get overall statistics for each :y category?

overall is really meant for all subjects together, but you also get statistics per group entry so I'm not sure what exactly you mean by `for each :y category`

> Is it possible to get grouping separately for :y and:z in one table?

No, currently not.

**Comment by PharmCat** [comment]
> overall is really meant for all subjects together, but you also get statistics per group entry so I'm not sure what exactly you mean by `for each :y category`

For example how tables in SPSS looks like:

![image](https://github.com/PumasAI/SummaryTables.jl/assets/13901158/aa54efd2-6449-44be-b827-f6fecd6e9b0f)

"Total" column can be printed for each sub-category.

**Comment by andreasnoack** [comment]
This would indeed be very useful to have.
